language: cpp
compiler: gcc
dist: trusty
sudo: false
before_script:
    - mkdir build
    - cd build
    - cmake -DTESTAPPS=ON ..
script:
    - make

notifications:
    #email:
        #- my.mail@foobar.com
    irc:
        - "irc.freenode.net#netport"

